---
- name: Install packages on servers
  hosts: all
  become: yes

  tasks:
    - name: Install packages on Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-11-jdk
        - python3
        - mysql-server
        - apache2
      when: ansible_distribution == 'Ubuntu'

    - name: Install packages on Amazon Linux
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - java
        - python3
        - httpd
      when: ansible_distribution == 'Amazon'