---
- name: install nginx package in system
<<<<<<< HEAD

=======
  become: yes
>>>>>>> 0633b276a1a935bc0ad6c74b0e51e88e0aacbb12
  hosts: all
  tasks:
    - name: install nginx in ubuntu
      apt:
        update_cache: yes
        name: nginx
        state: absent
      when: ansible_distribution == 'Ubuntu' 
    - name: install nginx in ubuntu 
      dnf:
        name: nginx
        state: absent
      when: ansible_distribution == 'Amazon' 
