---
- name: install apache2 package in system
  hosts: all
  tasks:
    - name: uninstall apache2 in ubuntu
      apt:
        update_cache: yes
        name: apache2
        state: absent
        autoremove: true
        purge: true
      when: ansible_distribution == 'Ubuntu' 
    - name: uninstall apache2 in amazon
      dnf:
        name: httpd
        state: absent
        autoremove: true
      when: ansible_distribution == 'Amazon' 
